;; (require 'chinese-fonts-setup)
;; (chinese-fonts-setup-enable)
;; (setq cfs-profiles
;;       '("coding" "read-code" "unset"))

;; font settings

;; Auto generated by chinese-fonts-setup
;; <https://github.com/tumashu/chinese-fonts-setup>

(defun use-font-set-ptmono ()
  (interactive)
  (set-face-attribute
   'default nil
   :font (font-spec :name "-*-PT Mono-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1"
                    :weight 'normal
                    :slant 'normal
                    :size 14.0))  ;; 20.0
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     (frame-parameter nil 'font)
     charset
     (font-spec :name "FZLiBian-S02S"
                :weight 'normal
                :slant 'normal
                :size 16.0))))  ;; 24.0

;; Auto generated by chinese-fonts-setup
;; <https://github.com/tumashu/chinese-fonts-setup>
(defun use-font-set-pragmata ()
  (interactive)
  (set-face-attribute
   'default nil
   :font (font-spec :name "-*-PragmataPro-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1"
                    :weight 'normal
                    :slant 'normal
                    :size 14.0)) ;; 20.0
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     (frame-parameter nil 'font)
     charset
     (font-spec :name "ZoomlaXige-A002"
                :weight 'normal
                :slant 'normal
                :size 14.0)))) ;; 20.0

(defun use-font-set-inziu ()
  (interactive)
  (set-default-font "Inziu IosevkaCC CL-16"))

(defun use-font-iosevka-slab ()
  (interactive)
  (set-default-font "Iosevka Slab-16"))

(defun use-font-fira-code ()
  (interactive)
  (set-default-font "Fira Code-12"))

(defun use-font-mononoki ()
  (interactive)
  (set-face-attribute
   'default nil
   :font (font-spec :name "-*-mononoki-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1"
                    :weight 'normal
                    :slant 'normal
                    :size 15.0))
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     (frame-parameter nil 'font)
     charset
     (font-spec :name "-*-Hiragino Sans GB-normal-normal-normal-*-*-*-*-*-p-0-iso10646-1"
                :weight 'normal
                :slant 'normal
                :size 16.5)))
  ;;  (set-default-font "mononoki-13")
  )





(defun use-font-monoid ()
  (interactive)
  (set-default-font "Monoid-12"))

(defun use-font-monoisome ()
  (interactive)
  (set-default-font "Monoisome-12"))

(defun my-buffer-face-mode-serif ()
  "Sets a fixed width (monospace) font in current buffer"
  (interactive)
  (setq buffer-face-mode-face '(:family "Times New Roman"))
  (buffer-face-mode))

(defun my-buffer-face-mode-caecilia ()
  "Sets a not fixed width font in current buffer(for read)"
  (interactive)
  (setq buffer-face-mode-face '(:family "Caecilia LT Std"))
  (buffer-face-mode))

;; (cl-prettyprint (font-family-list))

(provide 'setup-fonts)
